### ISSUE TITLE
Will WANN be a beta or stable module of tensorflow in the future?

### ISSUE THREAD

**Issue by oushu1zhangxiangxuan1** [weightagnostic/weightagnostic.github.io#13]
It‘s a great idea that sharing weights between all nodes in the network.
I've read the paper and the soure code in javascript of cart-pole,
but I didn't found code  of other tasks like car-racing and biped.

Would you release some more code in the future?
Will wann be added to tensorflow in the future as I saw that the authors are from Google Brain?

**Comment by UltronBrain** [comment]
个人感觉即使有代码发布，那肯定不是基于深度学习框架（tensorflow，pytorch等）的。类似于neat进化算法，希望是基于c语言或者c++的。

**Comment by weightagnostic** [comment]
Hi. Code is now released.

**Comment by oushu1zhangxiangxuan1** [comment]
Thanks ever so much !
